title: Manuel++
description: Un manuel pour Notepad++
permalink: /:collection/:name
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

collections:
  pages: # to organize pages in _pages/
    output: true
    permalink: /:path

plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings

# plugins config
relative_links:
  enabled:     true
  collections: true
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true