title: Manuel++
description: Un manuel pour Notepad++
lang: fr
permalink: /:collection/:name
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

baseurl: /nppmanuel

collections:
  pages: # organize pages in _pages/
    output: true
    permalink: /:path

# organise theme files in a directory
layouts_dir : _theme/_layouts
includes_dir : _theme/_includes
sass:
    sass_dir: _theme/_sass
    style: compressed

plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-tidy
  - jekyll-sitemap
  - jekyll-toc

# plugins config
relative_links:
  enabled:     true
  collections: true
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true
jekyll_tidy:
  compress_html: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      toc: true