title: Manuel++, un manuel pour Notepad++
description: Un manuel pour Notepad++
lang: fr
permalink: /:collection/:name

google_analytics:
  - UA-21458763-1
  - UA-21458763-6

repository: nliautaud/nppmanuel

collections:
  pages: # organize pages in _pages/
    output: true
    permalink: /:path

# organise theme files in a directory
layouts_dir : _theme/_layouts
includes_dir : _theme/_includes
sass:
    sass_dir: _theme/_sass
    style: compressed

defaults:
  - scope:
      path: images
    values:
      image: true

plugins:
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-sitemap

# plugins config
relative_links:
  enabled:     true
  collections: true
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true
jekyll_tidy:
  compress_html: true
readme_index:
  enabled:          true
  remove_originals: true